### PR TITLE
Fix typo in README.md

### PR DESCRIPTION
**Pull request by tomaszbakula**

### CODE REVIEW

**Comment by nelsonic** [comment]
@tomaszbakula thanks for fixing the typo. 👍 
We are investigating why the Travis-CI build is failing ... 🔍 ⌛️

**Comment by nelsonic** [comment]
@tomaszbakula could you please rebase on master to get the changes in `.travis.yml` and `package.json`? hopefully that will ensure that the build passes on your Pull Request and we can merge your typo fix. thanks! 👍

**Comment by tomaszbakula** [comment]
@nelsonic It looks like it's ok now but I'm not sure if I've done this correctly because I couldn't find the 7cca7ee9368edde936975c6cabe42cbcaba68c2b commit in the git log.

**Comment by nelsonic** [comment]
@tomaszbakula thanks for updating. 👍 
merge commits do not alter the state of the log they merely include commits from other branches/logs so don't worry about not finding it 😉 
Welcome to @dwyl ! ❤️  ✅  🚀

**Comment by tomaszbakula** [comment]
No worries @nelsonic :) it's always good to do something for the community, even such a small thing like a typo fix.

**Pull request merged**
