### PR TITLE
Rename 'authorization' header to 'x-access-token'

### PR DESCRIPTION
**Pull request by olizilla**
The readme refers to `x-access-token` as the header that'll be used to pass the token around in, but the code didn't. Now is do.

### CODE REVIEW

**Comment by nelsonic** [comment]
Ah...! Ciao @olizilla!
Sadly, its the *readme* that needs to be updated ... *My Bad* ... :disappointed: 
Our Hapi.js Plugin uses `request.headers.authorization` 
see: https://github.com/dwyl/hapi-auth-jwt2/blob/f62bf57795e22b97f5c31a2375b68d6e7e6b80e1/lib/extract.js#L21-L22

Its worth keeping it consistent because the plugin advises people to visit the this repo to learn more about JWTs ... thanks *so* much for drawing our attention to this!

**Comment by olizilla** [comment]
For my knowledge is `authorization` the generally preferred header name for this kind of thing? What was the backstory on the change?

**Comment by nelsonic** [comment]
Ah, we *was* using `x-access-token` but switched to using the (*standard*) `authorization` header because it was mentioned in the spec:
http://self-issued.info/docs/draft-ietf-oauth-json-web-token.html#rfc.section.1
(or RFC: http://www.rfc-editor.org/rfc/rfc7519.txt if you prefer ... you'll need to grep for it)

and it keeps it consistent with Hapi Auth Basic: 
https://github.com/hapijs/hapi-auth-basic/blob/ea5b694adeaf15b3df46243a5501394d6f3c9268/lib/index.js#L35

Also, there's industry trend (_best-practice_?) for it:
+ https://developer.atlassian.com/static/connect/docs/latest/concepts/authentication.html
+ http://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-auth-using-authorization-header.html
+ https://dev.twitter.com/oauth/overview/authorizing-requests

**Comment by olizilla** [comment]
@nelsonic ok so. Do you think the auth scheme should be prefixed into the header value, as it is with other schemes, Basic is prefixed with `Basic`, Digest has `Digest`... 
https://en.wikipedia.org/wiki/Digest_access_authentication

The Atlassian seems to do it with JWT:
```
Authorization" header value: "JWT <insert jwt-token here>"
```
https://developer.atlassian.com/static/connect/docs/latest/concepts/authentication.html

Perhaps a win for consistency at the expense of simplicity. I've no strong opinion. I guess as it's joining the masses in a commonly used header it'd be polite to follow suit.

**Comment by nelsonic** [comment]
Yeah, its easier to use the `authorization` _key_ because hapi automatically `toLowerCase()`es the header keys (so you don't have to remember if its upper/lower case) oh, and did I mention its one fewer character to type. :wink:

**Comment by nelsonic** [comment]
Does #39 superseded this PR?

**Comment by olizilla** [comment]
This PR is irrelevant now, but the question above is about the value for the Authorisation header. Should it be prefixes with JWT to denote the Authorisation method bei g used as per other styles like Basic et al?

**Comment by nelsonic** [comment]
We could probably have some sort of word to denote that the token is a JWT ...
But we are *assuming* that there will only be one token passed by the client.
A multiple token use-case has not yet surfaced ...

**Comment by nelsonic** [comment]
If we want to use basic auth, we simply register the https://github.com/hapijs/hapi-auth-basic plugin first and it will attempt to authenticate the user first in the request lifecycle.
But again, this use-case has not presented its' self.

If you are happy that the readme/demo app is consistent, please close the PR. 
(Sorry to have created work for you ... will buy you a :beer: next time we :bowling: )

**Pull request closed without merging**
